services:
  - type: web
    name: revoluxburger-backend
    env: docker
    plan: free
    repo: https://github.com/MarioAviles/revoluXburger-backend
    branch: main
    dockerfilePath: ./Dockerfile
