services:
  - type: web
    name: revoluxburger-backend
    env: docker
    plan: free
    repo: https://github.com/MarioAviles/revoluXburger-backend
    buildCommand: bash install-java.sh && bash mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
