# application-example.properties

# Nombre de la app
spring.application.name=backend

# Opción 1: Base de datos H2 (en memoria) - más fácil
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Opción 2 (alternativa): PostgreSQL local
#spring.datasource.url=jdbc:postgresql://localhost:5432/revoluxburger
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración general
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Supabase (rellenar si se quiere probar subida de imágenes)
supabase.url=REEMPLAZAR_CON_URL
supabase.bucket=REEMPLAZAR_CON_BUCKET
supabase.apikey=REEMPLAZAR_CON_API_KEY

# Email (rellenar si se quiere probar recuperación de contraseña)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=REEMPLAZAR_CON_EMAIL
spring.mail.password=REEMPLAZAR_CON_CONTRASEÑA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
